python train_simsiam.py \
      --data ShapeNetScan \
      --txt train_all.txt \
      --num_points 1024 \
      --backbone dgcnn\
      --multi 1.5 \
      --epochs 100 \
      --device 0,1,2,3 \
      --save 1 \
      --batch_size 80 \
      --seed 28 \
        --optimizer sgd \
        --scheduler warmup_cos \
        --lr 0.015625 \
        --weight_decay 0.0005 \
        --momentum 0.9 \
        --warmup_epoch 10 \
        --warmup_lr 0 \
        --final_lr 0 \
          --crop_size 512 \
          --project_hdim 2048 \
          --project_odim 2048 \
          --predict_hdim 512 \
          --proj_layers 2